### ISSUE TITLE
Substrate Development: Update Pallet + Relayer

### ISSUE THREAD

**Issue by waymobetta** [ChainSafe/chainbridge-substrate#113]
This epic is meant to house all issues related to the update/upgrade of the ChainBridge pallet. This epic is not limited to a certain number of tasks, as more tasks may be added in as they are discovered/determined to be relevant.

**Comment by ivanceras** [comment]
[Migrating](https://github.com/ivanceras/chainbridge-substrate/tree/migrate) the chainbridge pallet is still in the works. I've managed to solve most of the compilation errors in the pallet and in the tests, with the exception of anything related to Balances. I'll make a WIP PR to this main repo after I've clean up the code.
