### ISSUE TITLE
Fix token precision for balances > 128bits

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-substrate#89]
We've restricted the maximum balance size to 128bits here: https://github.com/ChainSafe/chainbridge-substrate/blob/73ec9d1349b55320c8e0e6a7f50f2dd7cc64eb05/example-pallet/src/lib.rs#L80

We should be able to modify this to allow for a conversion from whatever size the BalanceOf is to a U256. Requires further investigation.

**Comment by gilescope** [comment]
128bit numbers are really very big. U256 could lead to performance issues. Are you sure you really want to go there?

**Comment by ansermino** [comment]
@gilescope Yes, there are substrate-based chains which use 256bit balances which we should aim to support.
